import { BLEND_MODES } from "pixi.js";

/**
 * 叠加模式
 */
export const BlendModes = {
    /**
     * 正常模式
     */
    NORMAL: BLEND_MODES.NORMAL,
    /**
     * 叠加模式
     */
    ADD: BLEND_MODES.ADD,
    MULTIPLY: BLEND_MODES.MULTIPLY,
    SCREEN: BLEND_MODES.SCREEN,
    OVERLAY: BLEND_MODES.OVERLAY,
    DARKEN: BLEND_MODES.DARKEN,
    LIGHTEN: BLEND_MODES.LIGHTEN,
    COLOR_DODGE: BLEND_MODES.COLOR_DODGE,
    COLOR_BURN: BLEND_MODES.COLOR_BURN,
    HARD_LIGHT: BLEND_MODES.HARD_LIGHT,
    SOFT_LIGHT: BLEND_MODES.SOFT_LIGHT,
    DIFFERENCE: BLEND_MODES.DIFFERENCE,
    EXCLUSION: BLEND_MODES.EXCLUSION,
    HUE: BLEND_MODES.HUE,
    SATURATION: BLEND_MODES.SATURATION,
    COLOR: BLEND_MODES.COLOR,
    LUMINOSITY: BLEND_MODES.LUMINOSITY,
    NORMAL_NPM: BLEND_MODES.NORMAL_NPM,
    ADD_NPM: BLEND_MODES.ADD_NPM,
    SCREEN_NPM: BLEND_MODES.SCREEN_NPM,
    NONE: BLEND_MODES.NONE,
    SRC_IN: BLEND_MODES.SRC_IN,
    SRC_OUT: BLEND_MODES.SRC_OUT,
    SRC_ATOP: BLEND_MODES.SRC_ATOP,
    DST_OVER: BLEND_MODES.DST_OVER,
    DST_IN: BLEND_MODES.DST_IN,
    DST_OUT: BLEND_MODES.DST_OUT,
    DST_ATOP: BLEND_MODES.DST_ATOP,
    SUBTRACT: BLEND_MODES.SUBTRACT,
    SRC_OVER: BLEND_MODES.SRC_OVER,
    ERASE: BLEND_MODES.ERASE,
    XOR: BLEND_MODES.XOR,
}